esphome:
  name: sonoff_s20
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "TF2201"
  password: "1234567890"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'mybays'

ota:
  password: 'mybays'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S20 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S20 Status"


switch:
  - platform: gpio
    name: "Sonoff S20 Relay"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: s20_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff S20 Green LED"
    output: s20_green_led
