substitutions:
  devicename: diningroomlamp

<<: !include secrets.yaml

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  build_path: build/$devicename


api:
  port: 6053
  reboot_timeout: 0s

# Enable logging
logger:


sensor:
  - platform: wifi_signal
    name: "${devicename}_wifi_signal"

output:
  - platform: gpio
    id: sonoff_basic_diningroom_light
    pin:
      number: GPIO12
      #inverted: True

light:
  - platform: binary
    name: "餐厅灯"
    output: sonoff_basic_diningroom_light
    restore_mode: RESTORE_DEFAULT_ON

