substitutions:
  devicename: iqairfan

<<: !include secrets.yaml

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  build_path: build/$devicename

api:
  port: 6053
  reboot_timeout: 0s

# Enable logging
logger:


sensor:
  - platform: wifi_signal
    name: "${devicename}_wifi_signal"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "IQAir Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "IQAir Status"


switch:
  - platform: gpio
    name: "IQAir Relay"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: iqair_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "IQAir Green LED"
    output: iqair_green_led
