substitutions:
  devicename: "espremote"

esphome:
  name: $devicename
  build_path: build/$devicename

esp8266:
  board: esp_wroom_02

<<: !include secrets.yaml

# Enable logging
logger:



output:
  - platform: gpio
    id: "blue_led"
    pin: GPIO15


switch:
  - platform: output
    id: "relay"
    name: "${devicename} Relay"
    output: "blue_led"


binary_sensor:
  - platform: gpio
    name: "${devicename} Boot"
    pin:
      number: GPIO0
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms

  - platform: gpio
    name: "${devicename} User"
    pin:
      number: GPIO4
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms


remote_receiver:
  pin:
    number: GPIO12
    inverted: True
  dump: all
  

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%